name: V2er
options:
  bundleIdPrefix: v2er
  deploymentTarget:
    iOS: "18.0"
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  developmentLanguage: zh-Hans

configFiles:
  Debug: Version.xcconfig
  Release: Version.xcconfig

settings:
  base:
    SWIFT_VERSION: "5.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false
    DEVELOPMENT_TEAM: DZCZQ4694Z
    CODE_SIGN_STYLE: Automatic

packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    branch: master
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    version: 2.0.0
  SwiftUI-WebView:
    url: https://github.com/kylehickinson/SwiftUI-WebView
    version: 0.3.0
  SwiftRichText:
    url: https://github.com/sethcreate/SwiftRichText
    revision: 86d3f06a48d1641e348f162afc99832b42cb9ce9

targets:
  V2er-iOS:
    type: application
    platform: iOS
    sources:
      - path: V2er
        excludes:
          - "**/.DS_Store"
          - Info.plist
      - path: V2er-iOS
        excludes:
          - "**/.DS_Store"
          - Info.plist
    dependencies:
      - package: Kingfisher
      - package: SwiftSoup
      - package: SwiftUI-WebView
        product: WebView
      - package: SwiftRichText
        product: Atributika
    settings:
      base:
        INFOPLIST_FILE: V2er-iOS/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: v2er.app
        PRODUCT_NAME: V2er
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    entitlements:
      path: V2er-iOS/V2er.entitlements

  V2er-macOS:
    type: application
    platform: macOS
    sources:
      - path: V2er
        excludes:
          - "**/.DS_Store"
          - Info.plist
      - path: V2er-macOS
        excludes:
          - "**/.DS_Store"
          - Info.plist
    dependencies:
      - package: Kingfisher
      - package: SwiftSoup
      - package: SwiftUI-WebView
        product: WebView
      - package: SwiftRichText
        product: Atributika
    settings:
      base:
        INFOPLIST_FILE: V2er-macOS/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: v2er.app
        PRODUCT_NAME: V2er
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_ENTITLEMENTS: V2er-macOS/V2er.entitlements
      configs:
        Debug:
          ENABLE_HARDENED_RUNTIME: false
        Release:
          ENABLE_HARDENED_RUNTIME: true

  V2erTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: V2erTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: V2er-iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.lessmore.V2erTests
        PRODUCT_NAME: V2erTests

  V2erUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: V2erUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: V2er-iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.lessmore.V2erUITests
        PRODUCT_NAME: V2erUITests
        TEST_TARGET_NAME: V2er-iOS

schemes:
  V2er-iOS:
    build:
      targets:
        V2er-iOS: all
        V2erUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - V2erTests
        - V2erUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  V2er-macOS:
    build:
      targets:
        V2er-macOS: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
